FROM ubuntu as build-env
RUN apt update
RUN apt install -y gcc libnl-3-dev libnl-route-3-dev pkg-config
WORKDIR /app
COPY . .
# Compile the binaries
RUN gcc -o daemon.out sniffer.h tnl-c.h mobi-packets.h tnl-c.c mobi-packets.c sniffer.c mobility-daemon.c $(pkg-config --cflags --libs libnl-3.0 libnl-route-3.0)
FROM ubuntu
COPY --from=build-env /app/daemon.out /app/daemon.out
WORKDIR /app
RUN apt update
RUN apt install -y libnl-3-200 libnl-route-3-200
CMD ["sleep", "infinity"] 